## Task 1: NumPy Array Operations
○ Objective: Perform operations on NumPy arrays.
○ Instructions:
1. Create a NumPy array with 12 random integers between 1 and 50.
2. Reshape the array into a 3x4 matrix.
3. Find and print the maximum, minimum, and mean values of the array

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 51, size=12)
print(arr)

[21 22  8 15 16 18 23 42 37 32  8 22]


In [3]:
new_arr = arr.reshape(3,4)
print(new_arr)

[[21 22  8 15]
 [16 18 23 42]
 [37 32  8 22]]


In [4]:
max_value = arr.max()
print(max_value)

42


In [5]:
min_value = arr.min()
print(min_value)

8


In [6]:
mean_value = arr.mean()
print(mean_value)

22.0


## Task 2: Array Indexing and Slicing
○ Objective: Practice indexing and slicing with NumPy arrays.
○ Instructions:
1. Create a NumPy array of shape (4, 3) with values from 1 to 12.
2. Extract and print the second row of the array.
3. Extract and print a 2x2 submatrix from the top-left corner of the array.

In [7]:
arr2 = np.arange(1,13).reshape(4,3)
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
print(arr2[1 ,:])

[4 5 6]


In [9]:
print(arr2[:2, :2])

[[1 2]
 [4 5]]
